### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ProgramNoona** [ProgramNoona/Capstone2019AnimeReview#4]
The layout isn't terribly pretty at this point.  I'm working on it, but thought I'd make an issue out of it so that Norris knows. I know we need a dark background, but if there are any suggestions y'all would like to make, that's cool.

**Comment by ProgramNoona** [comment]
Eh.....Okay, so I'm playing around with stuff, and I'm having trouble making the sidebar appear when trying to copy it on the home page.  For now it's fine to just leave it on the layout page, because figuring out how to make it stay on the side of the page rather than appearing at the bottom is more than we need to bother about right now.

I'm playing around with the about page, and I should have something at the end of the week for it.

**Comment by Blythem8826** [comment]
When I tried to modify the sidebar, I ran into the issue of it only allowing one of the block contents so anything you do needs to be inside of that single one. The only problem was that the side bar's div class is written outside of the block content which means we cant use python code in that area.. I'm thinking that if we do indeed keep the sidebar, we could move it into the block comment to host something like that mini gallery idea that we talked about in class.

**Comment by ProgramNoona** [comment]
I'm about fed up with the sidebar.  It is just not doing what it is supposed to do.

Uh, as for other stuff, because the page sections are divided by <div> instead of by things like <section> and <article>, a lot of the layout stuff is unfortunately going to have to be done by page, due to the large number of <div> within <div>s going on.  It's not too big of a deal, just a little more work for me.

**Comment by ProgramNoona** [comment]
Is anyone else having trouble inserting pictures?

**Comment by ProgramNoona** [comment]
Okay, so I found this picture I'd like to be the background, and it's looking good so far, except for the fact that the picture will not show up on the site, despite me following all the image conventions.  Is there something special going on with how images are loaded?

**Comment by Blythem8826** [comment]
hmm if you could create a branch of the code you're working with I could take a look at it, that or send it to me directly. The pictures on the site are read from folders in which they are stored so maybe the path your using isn't quite matching up? If you don't see this tonight i'll take a look at it tomorrow in class.

**Comment by ProgramNoona** [comment]
Yaaaay!  I figured it out!  Turns out there was an href needed at the top of the page, plus some formatting stuff.  

Oh, and for some reason messing the with the background got rid of the shadow text.  No idea why.  Anyway, I'm going to start on converting the sidebar to the logo, then I'm going to start messing more with the about page.

**Comment by ProgramNoona** [comment]
Okay, LayoutAttempt1.zip is the file you need to receive the templates and the static folders.  Replacing those in your file should make it work.

**Comment by ProgramNoona** [comment]
Templates have been merged, prolly not enough time for any major changes.  It's pretty good, so, yeah.
