### ISSUE TITLE
Anime Input form Issue

### ISSUE THREAD

**Issue by AlexL-Productions** [ProgramNoona/Capstone2019AnimeReview#7]
On the website, a form (only available to admin) to literally create and add anime to the site was created but does not accomplish that. There are better ways to edit data but it could still serve a function. I have tried adding a couple new anime but they are not saved to the database (or the csv file thats used to import data) so it doesn't show up at all.

**Comment by BlytheS2564** [comment]
I fixed this up so it should now be working
